// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_comments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addCommentToArticle = `-- name: AddCommentToArticle :one
INSERT INTO article_comments(article_id, author_id, body)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, article_id, author_id, body
`

type AddCommentToArticleParams struct {
	ArticleID int64
	AuthorID  uuid.UUID
	Body      string
}

func (q *Queries) AddCommentToArticle(ctx context.Context, arg AddCommentToArticleParams) (ArticleComment, error) {
	row := q.db.QueryRowContext(ctx, addCommentToArticle, arg.ArticleID, arg.AuthorID, arg.Body)
	var i ArticleComment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArticleID,
		&i.AuthorID,
		&i.Body,
	)
	return i, err
}

const deleteCommentFromArticle = `-- name: DeleteCommentFromArticle :one
DELETE FROM article_comments
WHERE id = $1 AND author_id = $2
RETURNING id, created_at, updated_at, article_id, author_id, body
`

type DeleteCommentFromArticleParams struct {
	ID       int64
	AuthorID uuid.UUID
}

func (q *Queries) DeleteCommentFromArticle(ctx context.Context, arg DeleteCommentFromArticleParams) (ArticleComment, error) {
	row := q.db.QueryRowContext(ctx, deleteCommentFromArticle, arg.ID, arg.AuthorID)
	var i ArticleComment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArticleID,
		&i.AuthorID,
		&i.Body,
	)
	return i, err
}

const getCommentsFromArticle = `-- name: GetCommentsFromArticle :many
SELECT c.id, c.article_id, c.body, c.author_id, c.created_at, c.updated_at, a.username, a.bio, a.image, EXISTS (
  SELECT 1
  FROM user_follows uf
  WHERE uf.follower_id = $2 AND uf.following_id = c.author_id
) AS author_is_followed
FROM article_comments c
JOIN users a
ON a.id = c.author_id
WHERE c.article_id = $1
`

type GetCommentsFromArticleParams struct {
	ArticleID  int64
	FollowerID uuid.UUID
}

type GetCommentsFromArticleRow struct {
	ID               int64
	ArticleID        int64
	Body             string
	AuthorID         uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Username         string
	Bio              sql.NullString
	Image            sql.NullString
	AuthorIsFollowed bool
}

func (q *Queries) GetCommentsFromArticle(ctx context.Context, arg GetCommentsFromArticleParams) ([]GetCommentsFromArticleRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsFromArticle, arg.ArticleID, arg.FollowerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsFromArticleRow
	for rows.Next() {
		var i GetCommentsFromArticleRow
		if err := rows.Scan(
			&i.ID,
			&i.ArticleID,
			&i.Body,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Bio,
			&i.Image,
			&i.AuthorIsFollowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
