// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_favorites.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countFavorites = `-- name: CountFavorites :one
SELECT COUNT(*)
FROM article_favorites
WHERE article_id = $1
`

func (q *Queries) CountFavorites(ctx context.Context, articleID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFavorites, articleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const favoriteArticle = `-- name: FavoriteArticle :one
INSERT INTO article_favorites(article_id, user_id)
VALUES(
    $1,
    $2
)
RETURNING article_id, user_id, created_at
`

type FavoriteArticleParams struct {
	ArticleID int64
	UserID    uuid.UUID
}

func (q *Queries) FavoriteArticle(ctx context.Context, arg FavoriteArticleParams) (ArticleFavorite, error) {
	row := q.db.QueryRowContext(ctx, favoriteArticle, arg.ArticleID, arg.UserID)
	var i ArticleFavorite
	err := row.Scan(&i.ArticleID, &i.UserID, &i.CreatedAt)
	return i, err
}

const getArticleIsFavorite = `-- name: GetArticleIsFavorite :one
SELECT
    EXISTS (
        SELECT 1
        FROM article_favorites af2
        WHERE af2.article_id = $1
          AND af2.user_id = $2
    ) AS is_favorited
`

type GetArticleIsFavoriteParams struct {
	ArticleID int64
	UserID    uuid.UUID
}

func (q *Queries) GetArticleIsFavorite(ctx context.Context, arg GetArticleIsFavoriteParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, getArticleIsFavorite, arg.ArticleID, arg.UserID)
	var is_favorited bool
	err := row.Scan(&is_favorited)
	return is_favorited, err
}

const unfavoriteArticle = `-- name: UnfavoriteArticle :exec
DELETE FROM article_favorites
WHERE article_id = $1 AND user_id = $2
`

type UnfavoriteArticleParams struct {
	ArticleID int64
	UserID    uuid.UUID
}

func (q *Queries) UnfavoriteArticle(ctx context.Context, arg UnfavoriteArticleParams) error {
	_, err := q.db.ExecContext(ctx, unfavoriteArticle, arg.ArticleID, arg.UserID)
	return err
}
