// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article_comments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCommentToArticle = `-- name: AddCommentToArticle :one
INSERT INTO article_comments(article_id, author_id, body)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, article_id, author_id, body
`

type AddCommentToArticleParams struct {
	ArticleID int64
	AuthorID  uuid.UUID
	Body      string
}

func (q *Queries) AddCommentToArticle(ctx context.Context, arg AddCommentToArticleParams) (ArticleComment, error) {
	row := q.db.QueryRowContext(ctx, addCommentToArticle, arg.ArticleID, arg.AuthorID, arg.Body)
	var i ArticleComment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArticleID,
		&i.AuthorID,
		&i.Body,
	)
	return i, err
}

const getCommentsFromArticle = `-- name: GetCommentsFromArticle :many
SELECT id, created_at, updated_at, article_id, author_id, body FROM article_comments
WHERE article_id = $1
`

func (q *Queries) GetCommentsFromArticle(ctx context.Context, articleID int64) ([]ArticleComment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsFromArticle, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleComment
	for rows.Next() {
		var i ArticleComment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleID,
			&i.AuthorID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
