// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles(author_id, slug, title, description, body)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, author_id, slug, title, description, body
`

type CreateArticleParams struct {
	AuthorID    uuid.UUID
	Slug        string
	Title       string
	Description string
	Body        string
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.AuthorID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
	)
	return i, err
}

const deleteArticleById = `-- name: DeleteArticleById :exec
DELETE FROM articles
WHERE id = $1
`

func (q *Queries) DeleteArticleById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticleById, id)
	return err
}

const feedArticles = `-- name: FeedArticles :many
SELECT
    a.id, a.created_at, a.updated_at, a.author_id, a.slug, a.title, a.description, a.body,
    u.username,
    u.bio,
    u.image,
    array_agg(t.name ORDER BY t.name) FILTER (WHERE t.name IS NOT NULL)::text[] AS tags,
    (SELECT COUNT(*)
     FROM article_favorites af
     WHERE af.article_id = a.id
    ) AS favorites_count,
    EXISTS (
        SELECT 1
        FROM article_favorites af2
        WHERE af2.article_id = a.id
          AND af2.user_id = $1
    ) AS is_favorited
FROM articles a
JOIN users u
ON a.author_id = u.id
JOIN user_follows uf
ON uf.follower_id = $1 AND uf.following_id = a.author_id
LEFT JOIN article_tags at
ON at.article_id = a.id
LEFT JOIN tags t
ON t.id = at.tag_id
GROUP BY a.id, u.id
ORDER BY a.created_at DESC
LIMIT $2
OFFSET $3
`

type FeedArticlesParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type FeedArticlesRow struct {
	ID             int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	AuthorID       uuid.UUID
	Slug           string
	Title          string
	Description    string
	Body           string
	Username       string
	Bio            sql.NullString
	Image          sql.NullString
	Tags           []string
	FavoritesCount int64
	IsFavorited    bool
}

func (q *Queries) FeedArticles(ctx context.Context, arg FeedArticlesParams) ([]FeedArticlesRow, error) {
	rows, err := q.db.QueryContext(ctx, feedArticles, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedArticlesRow
	for rows.Next() {
		var i FeedArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.Username,
			&i.Bio,
			&i.Image,
			pq.Array(&i.Tags),
			&i.FavoritesCount,
			&i.IsFavorited,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT
    a.id, a.created_at, a.updated_at, a.author_id, a.slug, a.title, a.description, a.body,
    author.username,
    author.bio,
    author.image,
    array_agg(t.name ORDER BY t.name)::text[] AS tags,
    (SELECT COUNT(*)
     FROM article_favorites af
     WHERE af.article_id = a.id
    ) AS favorite_count
FROM articles a
JOIN users author ON author.id = a.author_id
LEFT JOIN article_tags at
ON at.article_id = a.id
LEFT JOIN tags t
ON t.id = at.tag_id
WHERE a.slug = $1
GROUP BY a.id, author.username, author.bio, author.image
`

type GetArticleBySlugRow struct {
	ID            int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	AuthorID      uuid.UUID
	Slug          string
	Title         string
	Description   string
	Body          string
	Username      string
	Bio           sql.NullString
	Image         sql.NullString
	Tags          []string
	FavoriteCount int64
}

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (GetArticleBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getArticleBySlug, slug)
	var i GetArticleBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.Username,
		&i.Bio,
		&i.Image,
		pq.Array(&i.Tags),
		&i.FavoriteCount,
	)
	return i, err
}

const getArticleIDBySlug = `-- name: GetArticleIDBySlug :one
SELECT id FROM articles WHERE slug = $1
`

func (q *Queries) GetArticleIDBySlug(ctx context.Context, slug string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getArticleIDBySlug, slug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getArticleTagsByArticleID = `-- name: GetArticleTagsByArticleID :many
SELECT t.name FROM tags t
JOIN article_tags at ON t.id = at.tag_id
JOIN articles a ON at.article_id = a.id
WHERE a.id = $1
`

func (q *Queries) GetArticleTagsByArticleID(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getArticleTagsByArticleID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticleBySlug = `-- name: UpdateArticleBySlug :one
UPDATE articles
SET title = COALESCE($1, title),
    body = COALESCE($2, body),
    description = COALESCE($3, description),
    slug = COALESCE($4, slug),
    updated_at = NOW()
WHERE slug = $5
RETURNING id, created_at, updated_at, author_id, slug, title, description, body
`

type UpdateArticleBySlugParams struct {
	Title       sql.NullString
	Body        sql.NullString
	Description sql.NullString
	NewSlug     sql.NullString
	Slug        string
}

func (q *Queries) UpdateArticleBySlug(ctx context.Context, arg UpdateArticleBySlugParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticleBySlug,
		arg.Title,
		arg.Body,
		arg.Description,
		arg.NewSlug,
		arg.Slug,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
	)
	return i, err
}
