// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: article.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO articles(author_id, slug, title, description, body)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, author_id, slug, title, description, body
`

type CreateArticleParams struct {
	AuthorID    uuid.UUID
	Slug        string
	Title       string
	Description string
	Body        string
}

func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.AuthorID,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Body,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Body,
	)
	return i, err
}

const createArticleTags = `-- name: CreateArticleTags :one
INSERT INTO article_tags (article_id, tag_id)
VALUES(
    $1,
    $2
)
RETURNING article_id, tag_id
`

type CreateArticleTagsParams struct {
	ArticleID int64
	TagID     int64
}

func (q *Queries) CreateArticleTags(ctx context.Context, arg CreateArticleTagsParams) (ArticleTag, error) {
	row := q.db.QueryRowContext(ctx, createArticleTags, arg.ArticleID, arg.TagID)
	var i ArticleTag
	err := row.Scan(&i.ArticleID, &i.TagID)
	return i, err
}

const createTags = `-- name: CreateTags :one
INSERT INTO tags (display_name, normalized_name)
VALUES(
    $1,
    $2
)
ON CONFLICT(
    normalized_name
)
DO UPDATE SET normalized_name = EXCLUDED.normalized_name
RETURNING id, created_at, updated_at, display_name, normalized_name
`

type CreateTagsParams struct {
	DisplayName    string
	NormalizedName string
}

func (q *Queries) CreateTags(ctx context.Context, arg CreateTagsParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTags, arg.DisplayName, arg.NormalizedName)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.NormalizedName,
	)
	return i, err
}
