// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Article struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AuthorID    uuid.UUID
	Slug        string
	Title       string
	Description string
	Body        string
}

type ArticleTag struct {
	ArticleID int64
	TagID     int64
}

type Tag struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Username       string
	Email          string
	HashedPassword string
	Bio            sql.NullString
	Image          sql.NullString
}

type UserFollow struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
	CreatedAt   time.Time
}
