// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package database

import (
	"context"
)

const createArticleTags = `-- name: CreateArticleTags :one
INSERT INTO article_tags (article_id, tag_id)
VALUES(
    $1,
    $2
)
RETURNING article_id, tag_id
`

type CreateArticleTagsParams struct {
	ArticleID int64
	TagID     int64
}

func (q *Queries) CreateArticleTags(ctx context.Context, arg CreateArticleTagsParams) (ArticleTag, error) {
	row := q.db.QueryRowContext(ctx, createArticleTags, arg.ArticleID, arg.TagID)
	var i ArticleTag
	err := row.Scan(&i.ArticleID, &i.TagID)
	return i, err
}

const createTags = `-- name: CreateTags :one
INSERT INTO tags (name)
VALUES(
    $1
)
ON CONFLICT(
    name
)
DO UPDATE SET name = EXCLUDED.name
RETURNING id, created_at, updated_at, name
`

func (q *Queries) CreateTags(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTags, name)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteArticleTagsByArticleID = `-- name: DeleteArticleTagsByArticleID :exec
DELETE FROM article_tags
WHERE article_id = $1
`

func (q *Queries) DeleteArticleTagsByArticleID(ctx context.Context, articleID int64) error {
	_, err := q.db.ExecContext(ctx, deleteArticleTagsByArticleID, articleID)
	return err
}

const getTags = `-- name: GetTags :many
SELECT name FROM tags
`

func (q *Queries) GetTags(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
