// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearUserBio = `-- name: ClearUserBio :one
UPDATE users
SET bio = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, username, email, hashed_password, bio, image
`

func (q *Queries) ClearUserBio(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, clearUserBio, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.Image,
	)
	return i, err
}

const clearUserImage = `-- name: ClearUserImage :one
UPDATE users
SET image = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, username, email, hashed_password, bio, image
`

func (q *Queries) ClearUserImage(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, clearUserImage, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.Image,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, hashed_password, bio, image)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, username, email, hashed_password, bio, image
`

type CreateUserParams struct {
	Username       string
	Email          string
	HashedPassword string
	Bio            sql.NullString
	Image          sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.Bio,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.Image,
	)
	return i, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const doesEmailExist = `-- name: DoesEmailExist :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE email = $1
)
`

func (q *Queries) DoesEmailExist(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, doesEmailExist, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const doesUsernameExist = `-- name: DoesUsernameExist :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE username = $1
)
`

func (q *Queries) DoesUsernameExist(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, doesUsernameExist, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, username, email, hashed_password, bio, image FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.Image,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, username, email, hashed_password, bio, image FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.Image,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, username, email, hashed_password, bio, image FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.Image,
	)
	return i, err
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
SET username = COALESCE($1, username),
    email = COALESCE($2, email),
    hashed_password = COALESCE($3, hashed_password),
    bio = COALESCE($4, bio),
    image = COALESCE($5, image),
    updated_at = NOW()
WHERE id = $6
RETURNING id, created_at, updated_at, username, email, hashed_password, bio, image
`

type UpdateUserByIDParams struct {
	Username       sql.NullString
	Email          sql.NullString
	HashedPassword sql.NullString
	Bio            sql.NullString
	Image          sql.NullString
	ID             uuid.UUID
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByID,
		arg.Username,
		arg.Email,
		arg.HashedPassword,
		arg.Bio,
		arg.Image,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.HashedPassword,
		&i.Bio,
		&i.Image,
	)
	return i, err
}
