// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_follow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const followUser = `-- name: FollowUser :one
INSERT INTO user_follows(follower_id, following_id)
VALUES (
    $1,
    $2
)
RETURNING follower_id, following_id, created_at
`

type FollowUserParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) (UserFollow, error) {
	row := q.db.QueryRowContext(ctx, followUser, arg.FollowerID, arg.FollowingID)
	var i UserFollow
	err := row.Scan(&i.FollowerID, &i.FollowingID, &i.CreatedAt)
	return i, err
}

const getFollowersOfUser = `-- name: GetFollowersOfUser :many
SELECT u.id, u.created_at, u.updated_at, u.username, u.email, u.hashed_password, u.bio, u.image
FROM users u
JOIN user_follows as uf
ON u.id = uf.follower_id
WHERE uf.following_id = $1
`

func (q *Queries) GetFollowersOfUser(ctx context.Context, followingID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getFollowersOfUser, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
			&i.HashedPassword,
			&i.Bio,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersFollowedByUser = `-- name: GetUsersFollowedByUser :many
SELECT u.id, u.created_at, u.updated_at, u.username, u.email, u.hashed_password, u.bio, u.image
FROM users u
JOIN user_follows as uf
ON u.id = uf.following_id
WHERE uf.follower_id = $1
`

func (q *Queries) GetUsersFollowedByUser(ctx context.Context, followerID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsersFollowedByUser, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
			&i.HashedPassword,
			&i.Bio,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1
    FROM user_follows
    WHERE follower_id = $1
      AND following_id = $2
)
`

type IsFollowingParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM user_follows
WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}
